*JJ McCauley*

## Classification on the Breast Cancer Dataset
#### Baseline Classifier (ANN)

In [28]:
''' Using Naive Bayes Classifier as Baseline, Loading Dataset, & Importing necessary dependencies '''
import pandas as pd
from sklearn.model_selection import train_test_split
import tensorflow as tf
from sklearn.datasets import load_breast_cancer
from sklearn.naive_bayes import GaussianNB

# Loading in data and splitting
loaded_bc_data = load_breast_cancer()
X = loaded_bc_data.data
y = loaded_bc_data.target
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=.3, random_state=42)

# Printing Num of feautes for hyperparameter tuning
print(X.shape[1]) 

# Printing Loaded Data to see how data is represented
print(X, "\n", y)  # Data is standardized and targets are 0, 1, so no modification is needed

# Using Naive Bayes Classifier as accuracy baseline
nbc_model1 = GaussianNB()
nbc_model1.fit(x_train, y_train)
nbc_model1_y_pred = nbc_model1.predict(x_test)
print(f"Baseline score for nbc_model1: {nbc_model1.score(x_test, y_test)}")

30
[[1.799e+01 1.038e+01 1.228e+02 ... 2.654e-01 4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 ... 1.860e-01 2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 ... 2.430e-01 3.613e-01 8.758e-02]
 ...
 [1.660e+01 2.808e+01 1.083e+02 ... 1.418e-01 2.218e-01 7.820e-02]
 [2.060e+01 2.933e+01 1.401e+02 ... 2.650e-01 4.087e-01 1.240e-01]
 [7.760e+00 2.454e+01 4.792e+01 ... 0.000e+00 2.871e-01 7.039e-02]] 
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 0 0 0 0 0 0 0 0 1 0 1 1 1 1 1 0 0 1 0 0 1 1 1 1 0 1 0 0 1 1 1 1 0 1 0 0
 1 0 1 0 0 1 1 1 0 0 1 0 0 0 1 1 1 0 1 1 0 0 1 1 1 0 0 1 1 1 1 0 1 1 0 1 1
 1 1 1 1 1 1 0 0 0 1 0 0 1 1 1 0 0 1 0 1 0 0 1 0 0 1 1 0 1 1 0 1 1 1 1 0 1
 1 1 1 1 1 1 1 1 0 1 1 1 1 0 0 1 0 1 1 0 0 1 1 0 0 1 1 1 1 0 1 1 0 0 0 1 0
 1 0 1 1 1 0 1 1 0 0 1 0 0 0 0 1 0 0 0 1 0 1 0 1 1 0 1 0 0 0 0 1 1 0 0 1 1
 1 0 1 1 1 1 1 0 0 1 1 0 1 1 0 0 1 0 1 1 1 1 0 1 1 1 1 1 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 1 1 1 1 1 1 0 1 0 1 1 0 1 1 0 1 0 0 1 1 1 1 1 1

In [23]:
''' ANN Model 1 '''
# Initializing ANN through tensorflow
adam_optimizier = tf.keras.optimizers.Adam(learning_rate=.001)
ANN_model1 = tf.keras.models.Sequential([
    tf.keras.layers.InputLayer(shape=(30,)),  # Input Layer - Each Feature to a Node
    tf.keras.layers.Dense(120, activation='relu'),  # First Dense Layer
    tf.keras.layers.Dropout(0.05),  # Dropout ~5% of Training Data to reduce overfitting
    tf.keras.layers.Dense(60, activation='relu'),  # Second Dense Layer
    tf.keras.layers.Dense(2, activation='softmax'),  # Last Dense Layer, classify as yes or no
])

ANN_model1.compile(optimizer=adam_optimizier, loss='sparse_categorical_entropy', metrics=['accuracy'])